### ISSUE TITLE
Feature: ensureTorunamentEntered option in submitScoreForPlayer

### ISSUE THREAD

**Issue by planadecu** [alexa-games/skills-gameon-sdk-js#12]
It would be nice that the `submitScoreForPlayer`function would support the flag `ensureTorunamentEntered` to automatically enter a tournament if the user has not. This feature already exists for a match as `ensureMatchEntered` but is not so useful if the user is not in a tournament.

Example usage:

```javascript
    await client.submitScoreForPlayer({ 
        matchId: GAMEON.matchId,
        submitScoreRequest: { score },
        player: alexaPlayer,
        ensureMatchEntered: true,
        ensureTournamentEntered: true,
    });
```

**Comment by superkew** [comment]
You would need to specify the tournamentId in the payload in the same way the matchId is submitted.

Please feel free to submit a PR for this.
https://github.com/alexa-games/skills-gameon-sdk-js/blob/develop/CONTRIBUTING.md
